// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type TcpNatIpv4KeyT struct {
	Pid   uint32
	Saddr uint32
	Daddr uint32
	Lport uint16
	Dport uint16
	Bytes uint64
}

// LoadTcpNat returns the embedded CollectionSpec for TcpNat.
func LoadTcpNat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpNatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpNat: %w", err)
	}

	return spec, err
}

// LoadTcpNatObjects loads TcpNat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpNatObjects
//	*TcpNatPrograms
//	*TcpNatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpNatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpNat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpNatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpNatSpecs struct {
	TcpNatProgramSpecs
	TcpNatMapSpecs
	TcpNatVariableSpecs
}

// TcpNatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpNatProgramSpecs struct {
	TcpSendmsg *ebpf.ProgramSpec `ebpf:"tcp_sendmsg"`
}

// TcpNatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpNatMapSpecs struct {
	TcpEvents *ebpf.MapSpec `ebpf:"tcp_events"`
}

// TcpNatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpNatVariableSpecs struct {
	UnusedIpv4KeyT *ebpf.VariableSpec `ebpf:"unused_ipv4_key_t"`
}

// TcpNatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpNatObjects struct {
	TcpNatPrograms
	TcpNatMaps
	TcpNatVariables
}

func (o *TcpNatObjects) Close() error {
	return _TcpNatClose(
		&o.TcpNatPrograms,
		&o.TcpNatMaps,
	)
}

// TcpNatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpNatMaps struct {
	TcpEvents *ebpf.Map `ebpf:"tcp_events"`
}

func (m *TcpNatMaps) Close() error {
	return _TcpNatClose(
		m.TcpEvents,
	)
}

// TcpNatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcpNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpNatVariables struct {
	UnusedIpv4KeyT *ebpf.Variable `ebpf:"unused_ipv4_key_t"`
}

// TcpNatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpNatPrograms struct {
	TcpSendmsg *ebpf.Program `ebpf:"tcp_sendmsg"`
}

func (p *TcpNatPrograms) Close() error {
	return _TcpNatClose(
		p.TcpSendmsg,
	)
}

func _TcpNatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpnat_x86_bpfel.o
var _TcpNatBytes []byte
